name: Generate domain-lists from v2fly/domain-list-community

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 22:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clone v2fly/domain-list-community
        run: |
          git clone --depth=1 https://github.com/v2fly/domain-list-community.git v2fly-data

      - name: Prepare output folder
        run: |
          mkdir -p output

      - name: Copy needed domain lists
        run: |
          cp v2fly-data/data/netflix output/Netflix.txt
          cp v2fly-data/data/youtube output/YouTube.txt
          cp v2fly-data/data/primevideo output/PrimeVideo.txt
          cp v2fly-data/data/disney output/Disney.txt
          cp v2fly-data/data/hbo output/HBO.txt
          cp v2fly-data/data/openai output/OpenAI.txt
          cp v2fly-data/data/tiktok output/TikTok.txt
          cp v2fly-data/data/spotify output/Spotify.txt

      - name: Show output files
        run: |
          ls -l output

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update domain-lists from v2fly/domain-list-community"
          file_pattern: 'output/*.txt'
