name: Generate Surge domain-lists from v2fly/domain-list-community

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clone v2fly/domain-list-community
        run: |
          git clone --depth=1 https://github.com/v2fly/domain-list-community.git v2fly-data

      - name: Prepare output folder
        run: |
          mkdir -p output

      - name: Generate cleaned Netflix list
        run: |
          grep '^full:' v2fly-data/data/netflix \
            | sed 's/^full://' \
            | sed 's/ //g' \
            > output/Netflix.txt

      - name: Generate cleaned YouTube list
        run: |
          grep '^full:' v2fly-data/data/youtube \
            | sed 's/^full://' \
            | sed 's/ //g' \
            > output/YouTube.txt

      - name: Generate cleaned OpenAI list
        run: |
          grep '^full:' v2fly-data/data/openai \
            | sed 's/^full://' \
            | sed 's/ //g' \
            > output/OpenAI.txt

      - name: Show output files
        run: |
          ls -l output
          cat output/Netflix.txt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update cleaned domain-lists for Surge"
          file_pattern: 'output/*.txt'
