name: Generate Surge domain-lists from v2fly/domain-list-community

on:
  schedule:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clone v2fly/domain-list-community
        run: |
          git clone --depth=1 https://github.com/v2fly/domain-list-community.git v2fly-data

      - name: Prepare output folder
        run: |
          mkdir -p output

      # Netflix
      - name: Generate cleaned Netflix list
        run: |
          cat v2fly-data/data/netflix | \
            grep -E '^(full|suffix):' | \
            sed 's/^[a-z]*://' | \
            sed 's/ //g' | \
            grep -Ev '[^a-zA-Z0-9.-]' | \
            sort | uniq > output/Netflix.txt

      # YouTube
      - name: Generate cleaned YouTube list
        run: |
          cat v2fly-data/data/youtube | \
            grep -E '^(full|suffix):' | \
            sed 's/^[a-z]*://' | \
            sed 's/ //g' | \
            grep -Ev '[^a-zA-Z0-9.-]' | \
            sort | uniq > output/YouTube.txt

      # OpenAI
      - name: Generate cleaned OpenAI list
        run: |
          cat v2fly-data/data/openai | \
            grep -E '^(full|suffix):' | \
            sed 's/^[a-z]*://' | \
            sed 's/ //g' | \
            grep -Ev '[^a-zA-Z0-9.-]' | \
            sort | uniq > output/OpenAI.txt

      - name: Show output files
        run: |
          echo "=== Netflix.txt ==="
          cat output/Netflix.txt
          echo "=== YouTube.txt ==="
          cat output/YouTube.txt
          echo "=== OpenAI.txt ==="
          cat output/OpenAI.txt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update cleaned domain-lists for Surge"
          file_pattern: 'output/*.txt'
